### ISSUE TITLE
Background not visible.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#10]
Feature request more than an issue:
The website background is simply dope, and we should capitalize on this.
At the moment, the background is briefly displayed when one accesses the website, but then it's covered in text. This is a nice compromise solution.
Improvement proposal: If one scrolls the text all the way down, after the text finishes the background is visible again. This can be done adding some transparent space after the purple text box and making the black bar with slack/twitter/... thinner.

**Comment by antonleviathan** [comment]
Same problem as in #8
