### ISSUE TITLE
Different tables are not aligned properly.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#14]
Different tables in the Zlarin talks page are not aligned properly. Zoom the page far out to understand what I'm talking about.

**Comment by emideluxe** [comment]
tables look fine. will close the issue.

**Comment by FabrizioRomanoGenovese** [comment]
They do not, see the image. Please do not too quick in closing an issue, they are open for a reason.
![Misaligned separators](https://imgur.com/a/2EJ9y)

**Comment by wires** [comment]
this is known / understandable because they are different tables. This can be fixed by using a single table. I don't find it super important to spend time on, so I'd say wontfix for now, unless someone feels inspired.

**Comment by FabrizioRomanoGenovese** [comment]
I just found out we don't have a wontfix label D:

Well, this issue can be referenced as a subproblem in the bigger "statebox restyling" one, if you like.

**Comment by emideluxe** [comment]
@FabrizioRomanoGenovese sorry, i had a look at it with bert earlier today and i guess we misunderstood what was not aligned properly.

**Comment by FabrizioRomanoGenovese** [comment]
It's not a huge issue unless one is on a 4K monitor, I just wanted to point out that it is there. Probably I should have attached an image from the very beginning!

**Comment by wires** [comment]
probably no longer relevant when this is merged https://github.com/statebox/statebox.github.io/pull/40
