### ISSUE TITLE
Statebox restyling.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#15]
I am filing a 

- **Task** (general, non-software related thing that needs to happen)

Importance

- **Critical** (critical to the current delivery timebox)

## Problem or idea

Now that the Zlarin summit has happened, we are gaining visibility. We have to change the background of the website as soon as possible, and revamp everything with a similar style.

## Solution or next step

- [x] Add "Talks" menu tab
- [x] Remove background
- [ ] Find a way to put a grid on the voxel
- [ ] Set voxel in place
- [ ] Revamp logo
- [ ] Keep the current colour scheme
- [ ] Add the chiptune javascript player

**Comment by emideluxe** [comment]
@antonleviathan we need a new menu tab called "talks" so that people can access the material which was filmed on zlaron without having to click on events.

**Comment by emideluxe** [comment]
I am closing this issue and opening a new one in PM.
