### ISSUE TITLE
Start drafting a 'Monograph' tab

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#18]
Monograph is far from being finished, but being it a markdown file it should be very easy to turn it into an interactive page. It would be very nice to start looking at how to implement this on the website.

The idea is to have a tab (next to "research" maybe) saying "monograph", that is just an html version of the monograph. On this page we should also provide an option to download the monograph as PDF (that again I suppose it can be easily done converting the markdown file to pdf).

Having this ready to fly would probably make our workflow faster when the right time comes!

**Comment by wires** [comment]
monograph is being rendered to a single HTML file now: https://github.com/statebox/monograph ; still needs work

**Comment by wires** [comment]
migrated to https://github.com/statebox/pm/issues/155
