### ISSUE TITLE
Start drafting team member's pages.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#22]
I am filing a 

- **Feature Request**
- **Support Request** (you need help)
- **Task** (general, non-software related thing that needs to happen)

Importance

- **Must have** (critical to the current delivery timebox)

## Context

Chris is about to publish his post on John Baez' blog. We will have a lot of views after this happens and we need to be prepared.

## Problem or idea

It is fundamental to give some infos about who we are, and how can people reach us. We should aim for something more than the usual, arid ass-faced photo of each team member that you can find in any ICO team page.

## Solution or next step

We need to draft a basic template for each member page. The idea is that on the `team` webpage there will be our names and photos. These should be clickable and let the user land on a page with more details provided, for each team member.

I have drafted a small document showing some of the main things that should be provided, for each team member. The link is below, feel free to make changes.
https://hackmd.io/OwIwrAxsDMCMIFpZgBywQFhQTgCYL10XmgAZYAzMANhACZpgg===#

## General considerations
We have to act quick if we want to capitalize on the momentum after Baez'blog publication.

**Comment by emideluxe** [comment]
jelle will create a yaml template and everyone can add the info on there. jelle is also asking a friend if he can make the visual format as displayed (more or less) in the example fabrizio provided.

**Comment by emideluxe** [comment]
also, I would remove the 'nationality' slot as it seems outdated. nation states suck.

**Comment by FabrizioRomanoGenovese** [comment]
I agree, if one feels like he should specify where is from this can be done in the Trivia section :)

**Comment by emideluxe** [comment]
@bertspaan ^

**Comment by wires** [comment]
there is a branch `pr/people`

**Comment by FabrizioRomanoGenovese** [comment]
I added my pic and file to the folder. I also created a new 'github' field, that I think is relevant for what we do. Feel free to erase it out if you don't like it.

**Comment by wires** [comment]
@emideluxe @antonleviathan @FabrizioRomanoGenovese can you collect some pixel art that you like? just pust it in a comment here. I need it for Thijs

![collection-8-bit-art-7](https://user-images.githubusercontent.com/315734/35232338-87101fb0-ff9b-11e7-9357-167e746af88b.jpg)
![collection-8-bit-art-4](https://user-images.githubusercontent.com/315734/35232339-872e520a-ff9b-11e7-9ba7-51e0fd304385.jpg)
![collection-8-bit-art-3](https://user-images.githubusercontent.com/315734/35232340-8749c6d4-ff9b-11e7-8e67-707ad076435f.jpg)
![collection-8-bit-art-2](https://user-images.githubusercontent.com/315734/35232346-8774e5ee-ff9b-11e7-8af8-e5743b54b749.jpg)

**Comment by FabrizioRomanoGenovese** [comment]
Something like this would work, flattening everything to a more monochromatic color scheme:
https://i.pinimg.com/236x/fa/38/ef/fa38ef1747c19edbf4271360da87b06e.jpg
https://i.pinimg.com/236x/b6/dd/22/b6dd22d65297b9572042c2c6f9d18f6e.jpg

**Comment by wires** [comment]
OK time expired to add graphics, I'm sending this to thijs.

**Comment by wires** [comment]
@bertspaan which picture to you want to get pixelified?
@difranco do you have a profile picture for us?
@FabrizioRomanoGenovese the image with the cat is super cool, but profile picture might be better for the pixel version (or higher resolution of the cat pic)

**Comment by wires** [comment]
@difranco what about this one? (cool picture btw)
![](https://oaklandnorth.net/wp-content/uploads/2015/12/20151211_INSULIN_Smith_ADF001-620x413.jpg)

@bertspaan do you want this one with the schmirk?
![](https://waag.org/sites/waag/files/public/styles/profile/public/Users/bert_spaan.jpg)

**Comment by FabrizioRomanoGenovese** [comment]
I can just crop my picture and leave the cat out, no probs

**Comment by dannce** [comment]
Now that I'm officially part of the team (!!), here is my picture:
![image](https://user-images.githubusercontent.com/11520820/35507442-1503bff6-04ed-11e8-9655-cf638d013bb2.png)

Please crop the picture if necessary.

**Comment by wires** [comment]
okay so what about this, is this good enough ?

![hicmbfkldkgojpcb](https://user-images.githubusercontent.com/315734/35970225-deb4b042-0cc9-11e8-8b4a-21da1f800ab6.png)

**Comment by FabrizioRomanoGenovese** [comment]
I think this should do. Maybe we just have to tweak the color scheme a bit to have the picture matching with the general style of the website, but I like it.

**Comment by wires** [comment]
closing this, will talk with thijs about a pixelization run on the team photos, tracked in statebox/pm#154
