### ISSUE TITLE
Setup and link to meetup

### ISSUE THREAD

**Issue by wires** [statebox/statebox.github.io#23]
We should have a link to the [Meetup page](www.meetup.com/Statebox) so that people from Netherlands can be "converted" to meetup members.

Also the Meetup page should be pimped, which depends on a new logo statebox/pm#59 and generally reusable visual bits.

**Comment by FabrizioRomanoGenovese** [comment]
Link is broken for me.

**Comment by emideluxe** [comment]
https://www.meetup.com/Statebox/

**Comment by emideluxe** [comment]
done.
