### ISSUE TITLE
Implement new site map

### ISSUE THREAD

**Issue by bertspaan** [statebox/statebox.github.io#27]
main ⟶
  - news ⟶
      - blog posts
      - twitter
  - events ⟶
      - events (see [Google Doc with events](https://docs.google.com/document/d/1j26V3x2EATvup8Ls57Dfhd7crrCNsrBErhNUCIsi7wM/edit#))
      - summits
      - meetup
  - about ⟶
      - team
      - careers
  - research ⟶
      - monograph

Page descriptions:

- news section should link to talks, blog posts about us, other news
- events section (events that we are organising and/or attending)
- careerz (current [jobs postings](https://github.com/statebox/pm/issues/58))
- about / what is statebox
- team / advisors / external researchers / contributors
    - details page for each person
    - overview page for: team
- button to monograph (white paper in the future) (`book.statebox.org`? and have it passwd protected?- invitation based)
- research page, has list of research topics for each topic, link to the researchers

**Comment by wires** [comment]
duplicate statebox/pm#85
