### ISSUE TITLE
Update image - add parallax scrolling

### ISSUE THREAD

**Issue by bertspaan** [statebox/statebox.github.io#31]
See https://github.com/statebox/pm/issues/26:

Maybe use @antonleviathan's [SVG logo](https://drive.google.com/drive/u/1/folders/1MgUFf7PKGbH2UfmGo-2v532s0LfYjny4) to recreate https://weaver-manifests-37554.netlify.com.

**Comment by wires** [comment]
sounds good, I used a JS lib for the parallax, check the trippy-site repo

**Comment by wires** [comment]
has been merged already
