### ISSUE TITLE
Rearrange Background for mobile version.

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [statebox/statebox.github.io#9]
The background is not displayed correctly in the mobile version and even the "Statebox" thing is not really readable. The image is too wide. Rescaling it mantaining the proportions should be optimal, if this is not possible then the image has to be narrowed to make it fit and something has to be added above and below to make it consistent. An easy solution would be just to fade top and bottom of the background towards black.

**Comment by antonleviathan** [comment]
Same problem as in #8 

But the idea with putting a solid color background with the image fitted to the screen width would work here so I'll do that for now.

**Comment by FabrizioRomanoGenovese** [comment]
hey mate @wires are you wankin or wat?

**Comment by antonleviathan** [comment]
This is finally fixed.
